### ISSUE TITLE
writing a row with a comma in it doesn't appear to be escaped

### ISSUE THREAD

**Issue by rozap** [plataformatec/nimble_csv#10]
I'd think a row with a comma in it would get quoted, but it doesn't seem to. I might be misunderstanding things entirely, but I've taken the example from here: https://en.wikipedia.org/wiki/Comma-separated_values#Basic_rules

Behaviour:
```elixir
iex> NimbleCSV.RFC4180.dump_to_iodata([[1997, "Ford", "E350", "Super, luxurious truck"]])
[["1997", 44, "Ford", 44, "E350", 44, "Super, luxurious truck", 10]]
```

What I'd expect
```elixir
iex> NimbleCSV.RFC4180.dump_to_iodata([[1997, "Ford", "E350", "Super, luxurious truck"]])
[["1997", 44, "Ford", 44, "E350", 44, "\"Super, luxurious truck\"", 10]]
```

Does nimblecsv expect commas in values will already be quoted? Or is this a bug?

**Comment by josevalim** [comment]
@rozap it does look like a bug.

**Comment by josevalim** [comment]
v0.1.1 is out with a fix.
