### ISSUE TITLE
current version defined in memory

### ISSUE THREAD

**Issue by hopewise** [plataformatec/nimble_csv#13]
I tried to call the API (in which I use NimpleCSV) for a second time, but I got this error:

    current version defined in memory

for line:

    NimbleCSV.define(MyParser, separator: ",", escape: "\"")

So, should I remove MyParser above when I finish? or shall I define it only once for all for API usage? where should that be?

**Comment by josevalim** [comment]
You must call it once, at the top of the file, and it will define a module that will be used across the project.
