### ISSUE TITLE
Generating CSV

### ISSUE THREAD

**Issue by djKooks** [plataformatec/nimble_csv#20]
Is there a module for generating CSV from data?
Sorry, but I couldn't find it. Thanks.

**Comment by josevalim** [comment]
Yes, all generated modules also have dump functions, for example this one: https://hexdocs.pm/nimble_csv/NimbleCSV.RFC4180.html#content

**Comment by djKooks** [comment]
@josevalim Oh, one more question. What I mean is, is there a direct module to generate CSV file from data, instead of dump => using IO module.
Thanks.
