### ISSUE TITLE
Compilation warning

### ISSUE THREAD

**Issue by cblavier** [plataformatec/nimble_csv#3]
The parser is working like a charm! However, it seems that the compiler doesn't understand that my CSVParser module is defined through a macro, it gives me a warning: 

```
function CSVParser.parse_stream/2 is undefined (module CSVParser is not available)
```

I'm using Elixir 1.3.0

**Comment by josevalim** [comment]
@cblavier can you provide a quick project that reproduces the error? Thank you!

**Comment by cblavier** [comment]
Here it is! https://github.com/cblavier/nimble_issue

**Comment by josevalim** [comment]
@cblavier it needs to be define outside of a function and outside of a module: https://github.com/cblavier/nimble_issue/blob/master/lib/nimble_issue.ex#L18

I will make the docs clearer as this is clearly our fault. :D

**Comment by josevalim** [comment]
Thank you for the feedback! 
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
