### ISSUE TITLE
parse_string/2 takes option `:headers`, but documentation says option is named `:header`

### ISSUE THREAD

**Issue by sparta-developers** [plataformatec/nimble_csv#30]
In the documentation, the option argument name claims to be `:header`:
https://github.com/plataformatec/nimble_csv/blob/v0.4.0/lib/nimble_csv.ex#L148

However, the tests and implementation use the option `:headers`:
https://github.com/plataformatec/nimble_csv/blob/v0.4.0/test/nimble_csv_test.exs#L17

It took us a little bit to figure out why the option wasn't working as expected.

**Comment by josevalim** [comment]
It has been fixed in master but I haven't pushed new docs. I have done that now, thanks!
