### ISSUE TITLE
Support of IANA standard for TSV

### ISSUE THREAD

**Issue by marcelotto** [plataformatec/nimble_csv#32]
From having a short look at the documentation and the code, it seems it's not possible to define a parser for the [IANA standard for TSV](https://www.iana.org/assignments/media-types/text/tab-separated-values) with NimbleCSV, since escaping is currently mandatory, but TSV works without any escaping by simply disallowing tabs in the values.

Am I missing something and defining a parser for TSV is already possible? If not, would it be hard to change the escaping behavior accordingly and were you willing to accept a PR?

**Comment by josevalim** [comment]
I think you can set the `:escape` to be `\t` itself (or the null byte) and set the reserved characters list to be empty, so the escaping character is never added while dumping.

**Comment by josevalim** [comment]
It is also worth noting that, if you have simply newlines and tabs, the implementation of parsing should be very straight-forward, a matter of calling :binary.split on the newlines and then split on tabs. Most of the code in NimbleCSV is exactly to handle the escaping bits.

**Comment by marcelotto** [comment]
I think both approaches should work fine. Thanks for your quick response and the whole project.

**Comment by marcelotto** [comment]
Just for the record and anyone else trying to define a proper IANA TSV parser with NimbleCSV: your first approach worked very well.

```elixir
NimbleCSV.define(TSV, separator: "\t", escape: "\0", reserved: [])
```

Since this is IMO not very obvious it might be worthwhile documenting it properly or better, since this is a standardized format, predefine it similar to the predefined `NimbleCSV.RFC4180` parser.

Thanks for your quick response and the whole project.
