### ISSUE TITLE
Support no escape character

### ISSUE THREAD

**Issue by TheFirstAvenger** [plataformatec/nimble_csv#38]
Setting `escape: nil` results in compilation errors.

**Comment by josevalim** [comment]
Can you please provide more information? Why do you need this feature? What is the sample file you are trying to parse or decode? Thank you.

**Comment by TheFirstAvenger** [comment]
In our case, we have a pipe separated file and we currently don't know if there is an escape character, but most likely there isn't.

**Comment by josevalim** [comment]
@TheFirstAvenger so my recommendation is just to set the escape character to something you know won't happen in your input, such as the null byte "\0". However, if you don't use escape characters, you probaby don't need this lib either, as your parser is simply a call to `String.split(line, "|")`.
