### ISSUE TITLE
Using fields from rows prevents the entire row from being freed

### ISSUE THREAD

**Issue by rschmukler** [plataformatec/nimble_csv#5]
Because larger binaries are stored as `Refc binaries`, the fields are stored as a `match contexts`, which means that using a single column from `parse_stream` or `parse_string` will prevent the entire origin string from being freed. This means that either `NimbleCSV` should automatically copy the data, or that it should be made very clear the implications of using a field from the row.

[Relevant Erlang Docs](http://erlang.org/doc/efficiency_guide/binaryhandling.html)

Perhaps `define` should create a parser which will copy by default (since this is a nasty side effect) but have an option to disable copying for power users.

**Comment by isaacsanders** [comment]
I am also interested in having an option to copy binaries.

**Comment by isaacsanders** [comment]
Most of the time, it is just the row binary that needs to be copied, rather than each field. The proposed solution in 6a3b4a9 is one end of the spectrum of solutions.
